config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :avatars, only: [:edit, :update, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  
  get 'contact', to: 'contact#new', as: 'contact'
  post 'contact', to: 'contact#create'
  
  post 'meetups/:meetup_id/rsvp', to: 'rsvps#create', as: 'rsvp_meetup'
  delete 'meetups/:meetup_id/rsvp', to: 'rsvps#destroy'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create'

  get 'register', to: "users#new", as: 'register'

  root 'home#index'

end

app/models/meetup.rb
class Meetup < ActiveRecord::Base

	has_and_belongs_to_many :users, through: :meetups_users
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
	
	authorize_resource only: [:new, :show, :edit, :update, :destroy]
	before_action :meetup, only: [:show, :edit, :update, :destroy]

	def index
		@meetups = Meetup.all
	end

	def new
		@meetup = Meetup.new
	end

	def create
		@meetup = Meetup.new(meetup_params)

		if @meetup.save
			flash[:success] = 'Meetup successfully created'
			redirect_to meetups_path
		else
			flash.now[:error] = 'Oops there was a problem...'
			render :new
		end
	end

	def show

	end

	def edit
	end

	def update
		if @meetup.update_attributes(meetup_params)
			flash[:success] = "Updated!"
			redirect_to @meetup
		else
			flash.now[:error] = 'Oops'
			render :edit
		end
	end

	def destroy
		if @meetup.destroy
			flash[:success] = 'Deleted!'
			redirect_to meetups_path
		end
	end

	private
		def meetup
			@meetup = Meetup.find(params[:id])
		end

		def meetup_params
			params.require(:meetup).permit(:name, :description, :address, :city, :zip, :state, :starts_at, :ends_at)
		end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/_form.html.erb
<fieldset>
	<%= form_for @meetup do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>
		<p>
			<%= f.label :address %>
			<%= f.text_field :address %>
		</p>
		<p>
			<%= f.label :city %>
			<%= f.text_field :city %>
		</p>
		<p>
			<%= f.label :state %>
			<%= f.text_field :state %>
		</p>
		<p>
			<%= f.label :zip %>
			<%= f.text_field :zip %>
		</p>
		<p>
			<%= f.label :starts_at %>
			<%= f.text_field :starts_at %>
		</p>
		<p>
			<%= f.label :ends_at %>
			<%= f.text_field :ends_at %>
		</p>
		<p>
			<%= f.label :description %>
			<%= f.text_area :description %>
		</p>

		<p class='actions'>
			<%= f.submit class: 'btn btn-primary'%>
			<%= link_to 'Cancel', meetups_path, class: 'btn' %>
		</p>
	<%end%>
</fieldset>

app/views/meetups/_meetup.html.erb
<section class="meetups">
	<h2><%= meetup.name %></h2>

	<h3>Location</h3>
	<%= meetup.address %>
	<%= "#{meetup.city}, #{meetup.state} #{meetup.zip}" %>

	<h3>Date and Time</h3>
	<p><strong>Starts At </strong><%= meetup.starts_at %></p> 
	<p><strong>Ends At </strong><%= meetup.ends_at %></p> 

	<h3>Description</h3>
	<p><%= meetup.description %></p>

	<div class='rsvp-info'>
		<%= render partial: 'rsvp', locals: {meetup: meetup}%>
	</div>
	<% if can? :manage, meetup %>
		<p class='actions'>
			<%= link_to 'Show', meetup, class:'btn'%>
			<%= link_to 'Delete', meetup, method: :delete, class:'btn btn-danger' %>
		</p>
	<%end%>
</section>

app/views/meetups/_rsvp.html.erb
<div class='well'>
	<% if current_user && current_user.rsvped_for_meetup?(meetup)%>
		<p>You're going to this meetup</p>
		<p><%= link_to 'Cancel RSVP', rsvp_meetup_path(meetup), class: 'btn btn-danger', method: :delete %></p>
	<%else%>
		<p>Would you like to attend this meetup?</p>
		<p><%= link_to 'RSVP for this meetup', rsvp_meetup_path(meetup), class: 'btn btn-primary', method: :post %></p>

	<%end%>
</div>

app/views/meetups/edit.html.erb
<h1>Edit Meetup</h1>
<%= render 'form' %>

app/views/meetups/index.html.erb
<div class='meetups'>
	<% if @meetups.present? %>
		<%= render @meetups %>
	<%else%>
		<p>Sorry! No Meetups yet :(</p>
	<%end%>

	<%if can? :manage, Meetup.new %>
		<p class='actions'>
			<%= link_to 'Add New Meetup', new_meetup_path, class:"btn btn-primary" %>
		</p>
	<%end%>
</div>

app/views/meetups/new.html.erb
<h1>New Meetup</h1>
<%= render 'form' %>

app/views/meetups/show.html.erb
<section class="meetups">
	<h2><%= @meetup.name %></h2>

	<h3>Location</h3>
	<%= @meetup.address %>
	<%= "#{@meetup.city}, #{@meetup.state} #{@meetup.zip}" %>

	<h3>Date and Time</h3>
	<p><strong>Starts At </strong><%= @meetup.starts_at %></p> 
	<p><strong>Ends At </strong><%= @meetup.ends_at %></p> 

	<h3>Description</h3>
	<p><%= @meetup.description %></p>

	<div class='rsvp-info'>
		<%= render partial: 'rsvp', locals: {meetup: meetup}%>
	</div>

	<hr>
	<% if can? :manage, meetup %>
		<p class='actions'>
			<%= link_to 'Edit', edit_meetup_path(@meetup), class: 'btn btn-primary'%>
			<%= link_to 'Cancel', meetups_path, class: 'btn' %>
		</p>
	<%end%>
</section>