config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :avatars, only: [:edit, :update, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  
  get 'contact', to: 'contact#new', as: 'contact'
  post 'contact', to: 'contact#create'
  
  post 'meetups/:meetup_id/rsvp', to: 'rsvps#create', as: 'rsvp_meetup'
  delete 'meetups/:meetup_id/rsvp', to: 'rsvps#destroy'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create'

  get 'register', to: "users#new", as: 'register'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save :hash_password

	validates :email, presence: true, uniqueness: true
	validates :password, confirmation: true, presence: { on: :create}
	

	has_and_belongs_to_many :meetups, through: :meetups_users
	has_one :profile, dependent: :destroy

	delegate :name, to: :profile, allow_nil: true
	delegate :age, to: :profile, allow_nil: true

	def hash_password
		if password_changed?
			write_attribute(:password, BCrypt::Password.create(password))
		end
	end

	def rsvp_for_meetup(meetup)
		meetups << meetup unless rsvped_for_meetup?(meetup)
	end

	def cancel_rsvp_for_meetup(meetup)
		meetups.delete(meetup) if rsvped_for_meetup?(meetup)
	end

	def rsvped_for_meetup? (meetup)
		meetups.include?(meetup)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	load_and_authorize_resource only: [:edit, :update, :destroy]
	before_action :authenticate!, only: [:edit, :update, :destroy]

	def index
		@users = User.includes(:profile).page(params[:page])
	end

	def new
		@user = User.new
		@profile = Profile.new
	end

	def edit
		@profile = @user.profile || Profile.new
	end

	def update
		@user.build_profile

		@user.assign_attributes user_params
		@user.profile.assign_attributes profile_params

		if @user.valid? && @user.profile.valid?
			@user.save
			flash[:success] = 'Updated profile successfully'
			redirect_to users_path
		else
			@user.profile.valid?
			@profile = @user.profile

			flash.now[:error] = 'A problem!'
			render :edit
		end
	end

	def create
		@user = User.new(user_params)
		@profile = Profile.new profile_params

		if @user.valid? && @profile.valid?
			@user.profile = @profile
			@user.save
			user_session.start_session @user
			flash[:success] = 'Account created and logged in successfully'
			redirect_to root_path
		else
			flash.now[:error] = 'Something went wrong'
			render :new
		end
	end

	def destroy
		logout = current_user.id == user.id
		@user.destroy
		user_session.destroy_session if logout
		flash[:success] = 'Your account has been successfully deleted'
		redirect_to users_path
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def profile_params
			params.require(:profile).permit(:name, :age)
		end

		def user
			@user = User.find(params[:id])
		end
end

app/views/users/edit.html.erb
<% if @user.errors.any? || @profile.errors.any? %>
		<ul>
			<% [@profile, @user].each do |resource| %>
				<% resource.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<%end%>
			<%end%>
		</ul>
	<%end%>
<div class="row-fluid">
	<div class='span6'>
		<%= form_for @user do |f| %>
			
			<%= fields_for @profile do |field| %>
				<div>
					<%= field.label :name %>
					<%= field.text_field :name %>
				</div>
				<div>
					<%= field.label :age %>
					<%= field.text_field :age %>
				</div>
			<%end%>	
			<div>
				<%= f.label :email %>
				<%= f.email_field :email %>
			</div>	
			<div>
				<%= f.submit class: 'btn btn-primary' %>
				<%= link_to 'Cancel', root_path, class: "btn" %>
			</div>
		<%end%>
	</div>
	<div class='span6'>
		<%= image_tag @user.profile.avatar.url, alt: @user.email %>
		<%= link_to 'Change Avatar', edit_avatar_path(@user), class: 'btn btn-success' %>
	</div>
</div>

app/views/users/index.html.erb
<div class='users'>
	<h1>Users</h1>
	<% if @users.present? %>
		<div>
			<ul>
				<% @users.each do |user| %>
					<li><%= image_tag user.profile.avatar.url, class: 'avatar-thumb'%> | <%= user.email%> | <%= user.name%> | <%= user.age %> | 
					<% if can? :manage, user %>
						<%= link_to 'Edit', edit_user_path(user), class: 'btn'%> | <%= link_to 'Delete', user, method: :delete, class: 'btn btn-danger'%>
					<%end%>
					</li>
				<%end%>
			</ul>
		</div>
	<%else%>
		<p>There are no users for this group.</p>
	<%end%>

	<% unless current_user %>
		<p><%= link_to 'Register for our User Group!', register_path, class: 'btn btn-primary' %></p>
	<%end%>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<%end%>
		</ul>
	<%end%>
	<div>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.label :password_confirmation, 'Confirm' %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div>
		<%= f.submit class: 'btn btn-primary' %>
		<%= link_to 'Cancel', root_path, class: "btn" %>
	</div>
<%end%>