config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :avatars, only: [:edit, :update, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  
  get 'contact', to: 'contact#new', as: 'contact'
  post 'contact', to: 'contact#create'
  
  post 'meetups/:meetup_id/rsvp', to: 'rsvps#create', as: 'rsvp_meetup'
  delete 'meetups/:meetup_id/rsvp', to: 'rsvps#destroy'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create'

  get 'register', to: "users#new", as: 'register'

  root 'home#index'

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController

	before_action :authenticate!
	before_action :user

	def edit	

	end

	def update
		if params[:profile].present?
			if user.profile.update_attributes avatar_params
				flash[:success] = 'File uploaded successfully'
			else
				flash[:error] = 'Something went wrong with the upload'
			end
		else
			flash[:error] = 'No file provided'
		end

		redirect_to edit_avatar_path(user)
	end

	def destroy
		if user.profile.avatar?
			user.profile.avatar = nil
			user.profile.save
			flash[:success] = 'File deleted successfully'
		else
			flash[:success] = 'There was no avatar to delete'
		end

		redirect_to edit_avatar_path(user)
	end

	private 

		def user
			@user ||= User.find params[:id]
			authorize! :manage, @user			
		end

		def avatar_params
			params.require(:profile).permit(:avatar)
		end
end

app/views/avatars/edit.html.erb
<div class='avatar-form'>
	<%= form_for @user.profile, url: avatar_path(@user), html: {multipart: true} do |f| %>
		<div>
			<%= f.label :avata, 'Upload new Avatar' %>
			<%= f.file_field :avatar %>
		</div>
		<p class='actions'>
			<%= f.submit 'Upload Avatar', class: 'btn btn-primary'%>
			<%= link_to 'Cancel', edit_user_path(@user), class: 'btn' %>
		</p>
	<%end%>
	<hr>
	<% if @user.profile.avatar? %>
		<%= image_tag @user.profile.avatar.url, alt: @user.email, class: 'avatar-thumb' %>
		<%= link_to 'Delete my Avatar', avatar_path(@user), class: 'btn btn-danger', method: :delete %>
	<%else%>
		<p>No Avatar</p>
	<%end%>
</div>