config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :avatars, only: [:edit, :update, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  
  get 'contact', to: 'contact#new', as: 'contact'
  post 'contact', to: 'contact#create'
  
  post 'meetups/:meetup_id/rsvp', to: 'rsvps#create', as: 'rsvp_meetup'
  delete 'meetups/:meetup_id/rsvp', to: 'rsvps#destroy'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create'

  get 'register', to: "users#new", as: 'register'

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Erie.rb Users Group</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <style type="text/css">
    body {
      padding-top: 60px;
      padding-bottom: 40px;
    }
    .sidebar-nav {
      padding: 9px 0;
    }
  </style>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="assets/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'Erie.rb', root_path, class: 'brand' %>
        <div class="nav-collapse collapse">
          <p class="navbar-text pull-right">
            <% if current_user %>
              <%= link_to "Welcome, #{current_user.email}", edit_user_path(current_user), class: 'navbar-link' %> |
              <%= link_to 'Logout', logout_path %>
            <% else %>
              <%= link_to 'Login', login_path %> |
              <%= link_to 'Register', register_path %>
            <% end %>
          </p>
          <ul class="nav">
            <li class="<%= params[:controller] == 'users' && 'active' %>"><%= link_to 'Users', users_path %></li>
            <li class="<%= params[:controller] == 'meetups' && 'active' %>"><%= link_to 'Meetups', meetups_path %></li>
            <% if current_user %>
              <li class="<%= params[:controller] == 'contact' && 'active' %>"><%= link_to 'Contact', contact_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <%= render 'shared/notifications' %>

        <%= yield %>
        
      </div><!--/span-->
    </div><!--/row-->
    <hr>
    <footer>
    <p>&copy; Company 2012</p>
    </footer>
  </div><!--/.fluid-container-->
</body>
</html>